README.md
=> write a description about our project

client/public/index.html, client/src/Components/App/App.js, client/src/Components/CommonComponent/Footer/Footer.css, client/src/Components/CommonComponent/Footer/Footer.js
=> create common component footer

client/public/index.html, client/src/Components/App/App.js, client/src/Components/CommonComponent/Footer/Footer.css, client/src/Components/CommonComponent/Footer/Footer.js
=> 44 add fonts

client/src/Components/CommonComponent/Input/index.css, client/src/Components/CommonComponent/Input/index.js
=> add some edits to input common component

client/.eslintrc.js, client/src/components/common/Header/index.js
remove disable rules for eslint destructing
=> fix destructing error in eslint

client/package-lock.json, client/src/components/App/index.css, client/src/components/App/index.js, client/src/components/common/Button/index.css, client/src/components/pages/SignUp/index.css, client/src/components/pages/SignUp/index.js
=> write signUp component with its style && edit style for button component

client/src/components/common/Card/data.js, client/src/components/common/Card/index.css, client/src/components/common/Card/index.js, client/src/components/pages/Activities/index.css, client/src/components/pages/Activities/index.js
…o set style for them
Relates #23
=> Pages | Activities - page

client/src/components/common/Card/data.js, client/src/components/common/Card/index.css, client/src/components/common/Card/index.js, client/src/components/common/StudentTable/index.css, client/src/components/common/StudentTable/index.js, client/src/components/pages/Activities/index.css, client/src/components/pages/Activities/index.js, client/src/components/pages/ParentProfile/index.css, client/src/components/pages/ParentProfile/index.js
=> 18 parent profile

client/src/components/App/index.js, client/src/components/pages/Subject/index.css, client/src/components/pages/Subject/index.js
=> Student subject 

client/src/components/common/Header/index.js
=> remove properties into state

client/src/components/common/Button/index.css, client/src/components/common/Input/index.css, client/src/components/pages/LogIn/index.css, client/src/components/pages/LogIn/index.js, client/src/components/pages/SignUpParent/index.css, client/src/components/pages/SignUpParent/index.js, client/src/components/pages/utils/signUpValidation.js
=>  validation schema | sign-up form

client/src/components/App/index.js, client/src/components/pages/HomeWork/data.js, client/src/components/pages/HomeWork/index.css, client/src/components/pages/HomeWork/index.js
relates #24
- create HomeWork Component .
- add style to Homework .
=> 24-make Homework component

.gitignore, .travis.yml, server/database/config/build.sql
relates #9
- add database Schema .
=> 9-database Schema

.gitignore, package.json, server/database/config/build.js, server/database/config/build.sql, server/database/config/connection.js, server/database/config/fakedata.sql
relates #16 
- add database connection file.    
- add build connection file .    
- add fake database file.
=> 16 database config

package-lock.json, package.json, server/app.js, server/controllers/index.js, server/router/index.js
install yup and move router from controllers to router
=> yup and router

package.json, server/app.js, server/controllers/index.js, server/controllers/routes/index.js, server/controllers/routes/logout.js, server/router/index.js, test/index.test.js, test/routes/index.test.js, test/routes/logout.test.js
=> logout route 

package-lock.json, server/app.js, server/controllers/middlewares/auth.js, server/controllers/middlewares/index.js, server/router/index.js, test/routes/cookie.test.js, test/routes/logout.test.js
relates #95 
- add auth to middlware .
- add index file to collect all middlewares and exports once .
=> 95- Auth middleware

client/src/components/App/index.css, client/src/components/App/index.js, client/src/components/common/Header/index.css, client/src/components/common/Menu/index.css, client/src/components/pages/Home/index.css, client/src/components/pages/Home/index.js
- add vision part 
- edits on the menu and header components 
- change place of buttons
=> Edit home page

.gitignore, package-lock.json, package.json, server/app.js, server/controllers/index.js, server/controllers/routes/homeworks.js, server/controllers/routes/login.js, server/controllers/routes/logout.js, server/controllers/routes/signupParent.js, server/controllers/utils/singupParentSchema .js, server/database/quieres/index.js, server/database/quieres/singup.js, server/router/index.js, test/index.test.js, test/quieres/index.test.js, test/quieres/singup.test.js, test/routes/index.test.js, test/routes/logout.test.js, test/routes/signupParent.test.js
=> 37 signup parent

server/controllers/index.js, server/controllers/middlewares/index.js, server/controllers/routes/teacherProfile.js, server/database/config/build.sql, server/database/config/fakedata.sql, server/database/quieres/teacherProfile.js, server/router/index.js, test/quieres/index.test.js, test/quieres/teacherProfile.js, test/routes/index.test.js, test/routes/teacherProfile.test.js
=> 39 teacher profile

client/package.json, server/controllers/index.js, server/controllers/routes/subjectPage.js, server/database/quieres/subjectPage.js, server/router/index.js, test/routes/index.test.js, test/routes/subjecrPage.test.js
=> 40 subject page

client/src/components/App/index.js, client/src/components/pages/SignUpParent/index.js, client/src/components/pages/utils/signUpValidation.js, server/controllers/utils/singupParentSchema .js, test/routes/signupParent.test.js
=> Create user  signup 

client/src/components/App/index.js, client/src/components/pages/TeacherProfile/index.js, server/controllers/routes/teacherProfile.js
=> axios to get teacher data

client/package.json, client/src/components/App/index.js, client/src/components/common/StudentTable/index.js, client/src/components/common/TeacherTable/index.js, client/src/components/pages/LogIn/index.js, client/src/components/pages/ParentProfile/index.js, client/src/components/pages/StudentProfile/index.js, client/src/components/pages/TeacherProfile/index.js, server/database/config/build.sql, server/database/config/fakedata.sql, server/database/quieres/parentProfile.js, server/database/quieres/teacherProfile.js, server/router/index.js, test/routes/subjecrPage.test.js
=> get parent-profile-data by using axios

server/app.js
=> add build stmt for client

client/src/components/App/index.js, client/src/components/common/Header/index.js, client/src/components/common/Menu/index.js, client/src/components/pages/LogIn/index.js, server/app.js, server/controllers/index.js, server/controllers/routes/auth.js, server/router/index.js
=> 103 post login

README.md
- edit the schema image due to changes that we done in the project. 
- write user journey as paragraph .
=> update readme data

server/database/config/fakedata.sql, test/index.test.js, test/quieres/getHomeworks.test.js, test/quieres/login.js, test/quieres/parentProfile.js, test/quieres/singup.test.js, test/quieres/teacherProfile.js, test/routes/classHomeworks.test.js, test/routes/login.test.js, test/routes/subjecrPage.test.js, test/routes/teacherProfile.test.js
=> some edits in fake data
